apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: account
  name: account
spec:
  ports:
    - name: "5001"
      port: 5001
      targetPort: 8080
  selector:
    io.kompose.service: account
