apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: account-db
  name: account-db
spec:
  ports:
    - name: "5435"
      port: 5435
      targetPort: 5432
  selector:
    io.kompose.service: account-db
