apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: account-db
  name: account-db
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: account-db
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        io.kompose.service: account-db
    spec:
      containers:
        - name: account-db
          image: postgres:latest
          ports:
            - containerPort: 5432
              protocol: TCP
          env:
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: ACCOUNT_DB
            - name: POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: ACCOUNT_DB_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: ACCOUNT_DB_PASSWORD
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: account-data
      restartPolicy: Always
      volumes:
        - name: account-data
          persistentVolumeClaim:
            claimName: account-data