services:
  account:
    build:
      context: ..
      dockerfile: src/account/Dockerfile
    container_name: account-service
    ports:
      - "5001:80"
    networks:
      - microservices

  payment:
    build:
      context: ..
      dockerfile: src/payment/Dockerfile
    container_name: payment-service
    ports:
      - "5002:80"
    networks:
      - microservices

  product:
    build:
      context: ..
      dockerfile: src/product/Dockerfile
    container_name: product-service
    ports:
      - "5003:80"
    networks:
      - microservices

  security:
    build:
      context: ..
      dockerfile: src/security/Dockerfile
    container_name: security-service
    ports:
      - "5004:80"
    networks:
      - microservices

  order:
    build:
      context: ..
      dockerfile: src/order/Dockerfile
    container_name: order-service
    ports:
      - "5005:80"
    networks:
      - microservices

    environment:
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_DATABASE=${POSTGRES_DATABASE}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    depends_on:
      - postgres_db

  postgres_db:
    image: postgres:latest
    container_name: postgres_db
    environment:
      - POSTGRES_DB=${POSTGRES_DATABASE}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    networks:
      - microservices

networks:
  microservices:
    driver: bridge

volumes:
  postgres_data:
