apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: order
  name: order
spec:
  ports:
    - name: "5005"
      port: 5005
      targetPort: 8080
  selector:
    io.kompose.service: order
