  apiVersion: apps/v1
  kind: Deployment
  metadata:
    labels:
      io.kompose.service: order-db
    name: order-db
  spec:
    replicas: 1
    selector:
      matchLabels:
        io.kompose.service: order-db
    strategy:
      type: Recreate
    template:
      metadata:
        labels:
          io.kompose.service: order-db
      spec:
        containers:
          - name: order-db
            image: postgres:latest
            ports:
              - containerPort: 5432
                protocol: TCP
            env:
              - name: POSTGRES_DB
                valueFrom:
                  configMapKeyRef:
                    name: app-config
                    key: ORDER_DB
              - name: POSTGRES_USER
                valueFrom:
                  configMapKeyRef:
                    name: app-config
                    key: ORDER_DB_USER
              - name: POSTGRES_PASSWORD
                valueFrom:
                  secretKeyRef:
                    name: db-credentials
                    key: ORDER_DB_PASSWORD
            volumeMounts:
              - mountPath: /var/lib/postgresql/data
                name: order-data
        restartPolicy: Always
        volumes:
          - name: order-data
            persistentVolumeClaim:
              claimName: order-data