apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: payment-db
  name: payment-db
spec:
  ports:
    - name: "5437"
      port: 5437
      targetPort: 5432
  selector:
    io.kompose.service: payment-db
