apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: payment
  name: payment
spec:
  ports:
    - name: "5002"
      port: 5002
      targetPort: 8080
  selector:
    io.kompose.service: payment
