apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: payment-db
  name: payment-db
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: payment-db
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        io.kompose.service: payment-db
    spec:
      containers:
        - name: payment-db
          image: postgres:latest
          ports:
            - containerPort: 5432
              protocol: TCP
          env:
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: PAYMENT_DB
            - name: POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: PAYMENT_DB_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: PAYMENT_DB_PASSWORD
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: payment-data
      restartPolicy: Always
      volumes:
        - name: payment-data
          persistentVolumeClaim:
            claimName: payment-data