apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: product-data
  name: product-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
