apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: product
  name: product
spec:
  ports:
    - name: "5003"
      port: 5003
      targetPort: 8080
  selector:
    io.kompose.service: product
