apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: product
  name: product
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: product
  template:
    metadata:
      labels:
        io.kompose.service: product
    spec:
      containers:
        - env:
            - name: POSTGRES_DATABASE
            - name: POSTGRES_HOST
            - name: POSTGRES_PASSWORD
            - name: POSTGRES_PORT
            - name: POSTGRES_USER
          image: product
          livenessProbe:
            exec:
              command:
                - curl
                - -f
                - http://localhost:8080/health
            failureThreshold: 3
            periodSeconds: 30
          name: product-service
          ports:
            - containerPort: 8080
              protocol: TCP
      restartPolicy: Always
