apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: product-db
  name: product-db
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: product-db
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        io.kompose.service: product-db
    spec:
      containers:
        - name: product-db
          image: postgres:latest
          ports:
            - containerPort: 5432
              protocol: TCP
          env:
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: PRODUCT_DB
            - name: POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: PRODUCT_DB_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: PRODUCT_DB_PASSWORD
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: product-data
      restartPolicy: Always
      volumes:
        - name: product-data
          persistentVolumeClaim:
            claimName: product-data