apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: product-db
  name: product-db
spec:
  ports:
    - name: "5436"
      port: 5436
      targetPort: 5432
  selector:
    io.kompose.service: product-db
