apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: security
  name: security
spec:
  ports:
    - name: "5004"
      port: 5004
      targetPort: 8080
  selector:
    io.kompose.service: security
