apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: security-db
  name: security-db
spec:
  ports:
    - name: "5438"
      port: 5438
      targetPort: 5432
  selector:
    io.kompose.service: security-db
