apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: security-db
  name: security-db
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: security-db
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        io.kompose.service: security-db
    spec:
      containers:
        - env:
            - name: POSTGRES_DB
            - name: POSTGRES_PASSWORD
            - name: POSTGRES_USER
          image: postgres:latest
          name: security-db
          ports:
            - containerPort: 5432
              protocol: TCP
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: security-data
      restartPolicy: Always
      volumes:
        - name: security-data
          persistentVolumeClaim:
            claimName: security-data
